# Generated by Django 4.2.3 on 2023-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
